"""add social posts table

Revision ID: 132405d87503
Revises: 8d4ab526ef37
Create Date: 2026-07-22 15:39:38.414848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132405d87503'
down_revision: Union[str, Sequence[str], None] = '8d4ab526ef37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_article_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('youtube', 'instagram', 'x', 'facebook', 'reddit', 'tiktok', 'other', name='social_platform', native_enum=False), nullable=False),
    sa.Column('external_post_id', sa.String(length=255), nullable=False),
    sa.Column('post_url', sa.String(length=2048), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('comment_count >= 0', name='ck_social_posts_comment_count'),
    sa.CheckConstraint('like_count >= 0', name='ck_social_posts_like_count'),
    sa.CheckConstraint('repost_count >= 0', name='ck_social_posts_repost_count'),
    sa.CheckConstraint('view_count >= 0', name='ck_social_posts_view_count'),
    sa.ForeignKeyConstraint(['news_article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_post_id', name='uq_social_post_platform_external_id'),
    sa.UniqueConstraint('post_url')
    )
    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_posts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_posts_news_article_id'), ['news_article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_posts_platform'), ['platform'], unique=False)

    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.alter_column('source_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_news_articles_evidence_score'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_articles_evidence_score'), ['evidence_score'], unique=False)
        batch_op.alter_column('source_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_posts_platform'))
        batch_op.drop_index(batch_op.f('ix_social_posts_news_article_id'))
        batch_op.drop_index(batch_op.f('ix_social_posts_id'))

    op.drop_table('social_posts')
    # ### end Alembic commands ###
