"""add_image_url_to_news_articles

Revision ID: 20df757dd0e1
Revises: a88b0dbc6029
Create Date: 2026-08-25 02:06:54.792855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20df757dd0e1'
down_revision: Union[str, Sequence[str], None] = 'a88b0dbc6029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
