"""add_user_productivity_tables

Revision ID: 39144c488d32
Revises: 3a156e761091
Create Date: 2026-08-29 21:48:10.191581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39144c488d32'
down_revision: Union[str, Sequence[str], None] = '3a156e761091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_saved_stories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['application_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'article_id', name='uq_user_saved_story')
    )
    with op.batch_alter_table('user_saved_stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_saved_stories_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_saved_stories_user_id'), ['user_id'], unique=False)

    op.create_table('user_source_watchlists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_domain', sa.String(length=255), nullable=False),
    sa.Column('source_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['application_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_domain', name='uq_user_source_watchlist')
    )
    with op.batch_alter_table('user_source_watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_source_watchlists_source_domain'), ['source_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_source_watchlists_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_source_watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_source_watchlists_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_source_watchlists_source_domain'))

    op.drop_table('user_source_watchlists')
    with op.batch_alter_table('user_saved_stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_saved_stories_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_saved_stories_article_id'))

    op.drop_table('user_saved_stories')
    # ### end Alembic commands ###
