"""Add Phase 2B lease and envelope fields

Revision ID: 3a156e761091
Revises: 410dc7af25ff
Create Date: 2026-08-29 19:31:53.587736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a156e761091'
down_revision: Union[str, Sequence[str], None] = '410dc7af25ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_webhook_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_payload', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('normalized_schema_version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('claimed_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('claim_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_webhook_events', schema=None) as batch_op:
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('claimed_at')
        batch_op.drop_column('claim_token')
        batch_op.drop_column('claimed_by')
        batch_op.drop_column('normalized_schema_version')
        batch_op.drop_column('normalized_payload')

    # ### end Alembic commands ###
