"""Add webhook retry fields

Revision ID: 410dc7af25ff
Revises: b44a820c5b3c
Create Date: 2026-08-29 18:59:42.111028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410dc7af25ff'
down_revision: Union[str, Sequence[str], None] = 'b44a820c5b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_webhook_events', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'processing_attempts',
                sa.Integer(),
                server_default='0',
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('processing_attempts', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_webhook_events', schema=None) as batch_op:
        batch_op.drop_column('next_retry_at')
        batch_op.drop_column('processing_attempts')

    # ### end Alembic commands ###
