"""create news articles table

Revision ID: 8d4ab526ef37
Revises: 
Create Date: 2026-07-22 13:06:07.101704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4ab526ef37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=150), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_score', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('comment_count >= 0', name='ck_news_comment_count'),
    sa.CheckConstraint('evidence_score BETWEEN 0 AND 100', name='ck_news_evidence_score'),
    sa.CheckConstraint('repost_count >= 0', name='ck_news_repost_count'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_articles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_evidence_score'), ['evidence_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_source_name'), ['source_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_articles_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_articles_title'))
        batch_op.drop_index(batch_op.f('ix_news_articles_source_name'))
        batch_op.drop_index(batch_op.f('ix_news_articles_region'))
        batch_op.drop_index(batch_op.f('ix_news_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_articles_id'))
        batch_op.drop_index(batch_op.f('ix_news_articles_evidence_score'))
        batch_op.drop_index(batch_op.f('ix_news_articles_category'))

    op.drop_table('news_articles')
    # ### end Alembic commands ###
