"""add_application_users_table

Revision ID: a363ce07e0ed
Revises: 31b4e80f2d9c
Create Date: 2026-08-29 00:34:40.171084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a363ce07e0ed'
down_revision: Union[str, Sequence[str], None] = '31b4e80f2d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auth_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('reader', 'reviewer', 'admin', name='user_role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_users_auth_subject'), ['auth_subject'], unique=True)
        batch_op.create_index(batch_op.f('ix_application_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_users_role'))
        batch_op.drop_index(batch_op.f('ix_application_users_email'))
        batch_op.drop_index(batch_op.f('ix_application_users_auth_subject'))

    op.drop_table('application_users')
    # ### end Alembic commands ###
