"""Add billing models

Revision ID: b44a820c5b3c
Revises: a363ce07e0ed
Create Date: 2026-08-29 01:56:30.270166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44a820c5b3c'
down_revision: Union[str, Sequence[str], None] = 'a363ce07e0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['application_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_customer_id', name='uq_billing_customer_provider_id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_billing_customer_user_provider')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('billing_customer_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('provider_plan_id', sa.String(length=255), nullable=False),
    sa.Column('plan_slug', sa.String(length=100), nullable=False),
    sa.Column('amount_subunits', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_interval', sa.String(length=50), nullable=False),
    sa.Column('provider_status', sa.String(length=50), nullable=False),
    sa.Column('local_status', sa.String(length=50), nullable=False),
    sa.Column('entitlement_tier', sa.String(length=50), nullable=False),
    sa.Column('access_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('cancellation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_provider_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_provider_event_id', sa.String(length=255), nullable=True),
    sa.Column('current_slot', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("current_slot IN ('current')", name='chk_current_slot_value'),
    sa.CheckConstraint('amount_subunits >= 0', name='chk_amount_non_negative'),
    sa.ForeignKeyConstraint(['billing_customer_id'], ['billing_customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['application_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subscription_id', name='uq_subscription_provider_sub_id'),
    sa.UniqueConstraint('user_id', 'current_slot', name='uq_subscription_user_current_slot')
    )
    op.create_table('billing_payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=False),
    sa.Column('provider_status', sa.String(length=50), nullable=False),
    sa.Column('amount_subunits', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_subunits >= 0', name='chk_payment_amount_non_negative'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_payment_id', name='uq_payment_provider_payment_id')
    )
    op.create_table('billing_webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('provider_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('safe_failure_code', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_webhook_provider_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_webhook_events')
    op.drop_table('billing_payments')
    op.drop_table('subscriptions')
    op.drop_table('billing_customers')
    # ### end Alembic commands ###
