"""add credibility assessments table

Revision ID: ed255c0d953b
Revises: 132405d87503
Create Date: 2026-07-22 17:28:52.853555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed255c0d953b'
down_revision: Union[str, Sequence[str], None] = '132405d87503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credibility_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_article_id', sa.Integer(), nullable=False),
    sa.Column('source_reliability_score', sa.Integer(), nullable=False),
    sa.Column('evidence_quality_score', sa.Integer(), nullable=False),
    sa.Column('corroboration_score', sa.Integer(), nullable=False),
    sa.Column('content_quality_score', sa.Integer(), nullable=False),
    sa.Column('credibility_score', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('method_version', sa.String(length=50), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('content_quality_score BETWEEN 0 AND 100', name='ck_credibility_content_score'),
    sa.CheckConstraint('corroboration_score BETWEEN 0 AND 100', name='ck_credibility_corroboration_score'),
    sa.CheckConstraint('credibility_score BETWEEN 0 AND 100', name='ck_credibility_overall_score'),
    sa.CheckConstraint('evidence_quality_score BETWEEN 0 AND 100', name='ck_credibility_evidence_score'),
    sa.CheckConstraint('source_reliability_score BETWEEN 0 AND 100', name='ck_credibility_source_score'),
    sa.ForeignKeyConstraint(['news_article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credibility_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credibility_assessments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credibility_assessments_news_article_id'), ['news_article_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credibility_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credibility_assessments_news_article_id'))
        batch_op.drop_index(batch_op.f('ix_credibility_assessments_id'))

    op.drop_table('credibility_assessments')
    # ### end Alembic commands ###
